CREATE TABLE users (
  id INT  AUTO_INCREMENT ,
  first_name VARCHAR(150) NOT NULL ,
  last_name VARCHAR(150) NOT NULL ,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  PRIMARY KEY (id) );